"""Plan the artwork for every catalog: writes generator/art.json from spec.json + a finished build (out/).

  python art_plan.py <build out dir>

Rules (per-slug overrides in art_overrides.json win):
  people      -> TMDB profile photo (poster); no photo -> their #1 title's backdrop
  franchise   -> first collection's backdrop
  everything else -> backdrop of the catalog's own #1 title, skipping backdrops already used in the same folder
  logos       -> streaming: provider icon; networks: network logo; studios: company logo
"""
import json, os, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build  # noqa: E402  (reuses its throttled, key-safe tmdb() and the durable cache)

HERE = Path(__file__).resolve().parent
LOOKAHEAD = 30        # titles tried per card before giving up on a unique backdrop


def backdrop(meta):
    media, tid = meta['type'], meta['id'].split(':', 1)[1]
    key = f"backdrop:{media}:{tid}"
    if key not in build._stable:
        d = build.tmdb(f"/{'movie' if media == 'movie' else 'tv'}/{tid}")
        build._stable[key] = d.get('backdrop_path')
    return build._stable[key]


def main():
    out = Path(sys.argv[1])
    spec = json.loads((HERE / 'spec.json').read_text(encoding='utf-8'))
    shapes = {f['key']: f['shape'] for f in spec['folders']}
    overrides = json.loads((HERE / 'art_overrides.json').read_text(encoding='utf-8')) \
        if (HERE / 'art_overrides.json').exists() else {}
    used = {}                                     # folder -> set of backdrop paths
    cards, problems = [], []
    try:
        for c in spec['catalogs']:
            shape = {shapes[f] for f in c['folders']}
            assert len(shape) == 1, f"{c['slug']}: folders with different shapes {c['folders']}"
            shape = shape.pop()
            assert (shape == 'poster') == (c['kind'] in ('director', 'actor')), f"{c['slug']}: people must be poster"
            card = {'slug': c['slug'], 'shape': shape, 'eyebrow': c['eyebrow'], 'title': c.get('art_title', c['title'])}
            metas = json.loads((out / 'catalog' / 'movie' / f"sd-{c['slug']}.json").read_text(encoding='utf-8'))['metas']
            folder_used = used.setdefault(c['folders'][0], set())
            if c['kind'] in ('director', 'actor'):
                card['bg'] = {'kind': 'person', 'id': c['person_id']}
            elif c['kind'] == 'franchise':
                card['bg'] = {'kind': 'collection', 'id': c['collection_ids'][0]}
            else:
                pick = None
                for m in metas[:LOOKAHEAD]:
                    path = backdrop(m)
                    if path and path not in folder_used:
                        pick = (m, path)
                        break
                if pick:
                    folder_used.add(pick[1])
                    card['bg'] = {'kind': 'path', 'path': pick[1], 'from': f"{pick[0]['name']} ({pick[0]['id']})"}
                else:
                    problems.append(f"{c['slug']}: no unused backdrop in the first {LOOKAHEAD} titles")
            p = c.get('movie', {}) if c['kind'] == 'discover' else {}
            q = c.get('series', {}) if c['kind'] == 'discover' else {}
            if 'with_watch_providers' in p:
                card['logo'] = {'kind': 'provider', 'id': int(p['with_watch_providers'].split('|')[0])}
            elif 'with_networks' in q:
                card['logo'] = {'kind': 'network', 'id': int(q['with_networks'])}
            elif 'with_companies' in p:
                card['logo'] = {'kind': 'company', 'id': int(p['with_companies'].split('|')[0])}
            card.update(overrides.get(c['slug'], {}))
            cards.append(card)
    finally:
        build.save_cache()
    (HERE / 'art.json').write_text(json.dumps({'_note': 'generated by art_plan.py; edit art_overrides.json instead',
                                               'cards': cards}, indent=1, ensure_ascii=False) + '\n', encoding='utf-8')
    print(f"art plan: {len(cards)} cards ({sum(c['shape'] == 'wide' for c in cards)} wide, "
          f"{sum(c['shape'] == 'poster' for c in cards)} poster), {build._calls[0]} TMDB requests")
    for p in problems:
        print('PROBLEM', p)
    sys.exit(1 if problems else 0)


if __name__ == '__main__':
    main()
